---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: github-actions-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: github-actions-backend
    spec:
      restartPolicy: Always
      containers:
      - name: github-actions-backend
        image: sauravdwivedi/github-actions-k8s-fullstack-backend:latest
        ports:
        - containerPort: 5000
---        
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: github-actions-backend
  type: LoadBalancer