---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: github-actions-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: github-actions-frontend
    spec:
      restartPolicy: Always
      containers:
      - name: github-actions-frontend
        image: sauravdwivedi/github-actions-k8s-fullstack-frontend:latest
        ports:
        - containerPort: 3000
---        
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: github-actions-frontend
  type: LoadBalancer