name: frontend-deployment

on:
  push:
    branches:
      - main
    paths:
      - github-actions-docker-fullstack/frontend/**
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: github-actions-docker-fullstack/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-docker-fullstack-frontend:latest
  docker-deploy:
    needs: docker-push
    runs-on: self-hosted
    steps:
      - run: echo deployment under construction
  check-container-logs:
    needs: [docker-push, docker-deploy]
    env:
      ASTERISKS: '**************************************************'
    runs-on: self-hosted
    steps:
      - run: echo ${{ env.ASTERISKS }}-frontend-logs-${{ env.ASTERISKS }}
      - run: docker logs `docker container ls | grep github-actions-frontend | awk '{print $1}'`