name: github-actions-k8s-fullstack-backend-deployment

on:
  push:
    branches:
      - main
    paths:
      - github-actions-k8s-fullstack/backend/** 
jobs:
  docker-push:
    runs-on: self-hosted
    env:
      WORK_DIR: ${{ github.workspace }}/github-actions-k8s-fullstack
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORK_DIR }}/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-k8s-fullstack-backend:latest
  docker-deploy:
    needs: docker-push
    runs-on: self-hosted
    steps:
      - run: kubectl create namespace backend || true
      - run: kubectl apply -f github-actions-k8s-fullstack/k8s/backend-deployment.yaml -n backend
  check-container-logs:
    needs: [docker-push, docker-deploy]
    env:
      ASTERISKS: '**************************************************'
    runs-on: self-hosted
    steps:
      - run: echo ${{ env.ASTERISKS }}-backend-logs-${{ env.ASTERISKS }}
      - run: kubectl logs -n backend `kubectl get pods -n backend --no-headers -o custom-columns=:metadata.name | head -1`