name: github-actions-k8s-fullstack-frontend-deployment

on:
  push:
    branches:
      - main
    paths:
      - github-actions-k8s-fullstack/frontend/**
jobs:
  docker-push:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: github-actions-k8s-fullstack/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-k8s-fullstack-frontend:latest
  docker-deploy:
    needs: docker-push
    runs-on: self-hosted
    steps:
      - run: kubectl create namespace frontend || true
      - run: kubectl apply -f github-actions-k8s-fullstack/k8s/frontend-deployment.yaml -n frontend
  check-container-logs:
    needs: [docker-push, docker-deploy]
    env:
      ASTERISKS: '**************************************************'
    runs-on: self-hosted
    steps:
      - run: echo ${{ env.ASTERISKS }}-frontend-logs-${{ env.ASTERISKS }}
      - run: kubectl logs -n frontend `kubectl get pods -n frontend --no-headers -o custom-columns=:metadata.name | head -1`