name: github-actions-docker-fullstack-deployment

on:
  push:
    branches:
      - main
    paths:
      - jenkins-docker-fullstack/backend/** 
      - jenkins-docker-fullstack/backend/**
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./jenkins-docker-fullstack/backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-docker-fullstack-backend:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-docker-fullstack-backend:latest
      - name: Build, tag and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: jenkins-docker-fullstack/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-docker-fullstack-frontend:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-docker-fullstack-frontend:latest